context:
  orig_ver: "3.0-9"
  sem_ver: "3.0.9"

package:
  name: raster3d
  version: ${{ sem_ver }}
source:
  url: http://www.bmsc.washington.edu/raster3d/Raster3D_${{ orig_ver }}.tar.gz
  sha256: 063edf90f107a57268a69b0801f6b7ff3a358bd596d1d617656611431033fa3a

build:
  number: 1

requirements:
  build:
    - ${{ compiler("m2w64_c") if win else compiler("c") }}
    - ${{ compiler("m2w64_fortran") if win else compiler("fortran") }}
    - ${{ stdlib("m2w64_c") if win else stdlib("c") }}
    # Temporary workaround for broken m2w64-sysroot build 11.
    # Remove after https://github.com/conda-forge/admin-requests/pull/2297 is applied.
    # See https://github.com/conda-forge/m2w64-sysroot-feedstock/issues/23
    - if: win
      then:
        - m2w64-sysroot_win-64 ==12.0.0.r4.gg4f2fc60ca hd8ed1ab_10
        - libwinpthread ==12.0.0.r4.gg4f2fc60ca h57928b3_10
    - ${{ "sed" if osx }}
    - ${{ "m2-base" if win }}
    - make
  host:
    - libgd
    - libjpeg-turbo
    - libpng
    - libtiff
  run_exports: []  # No shared libraries

tests:
  - script:
      - cd examples
      - if: unix
        then: |
          R3D_LIB=../materials render -gamma 1.1 -png example1.png < example1.r3d
          test -s example1.png
          R3D_LIB=../materials render -gamma 1.1 -tiff example1.tiff < example1.r3d
          test -s example1.tiff
      - if: win
        then: |
          set "R3D_LIB=../materials"
          render -gamma 1.1 -png example1.png < example1.r3d
          if not exist example1.png exit /b 1
          for %%F in (example1.png) do if %%~zF EQU 0 exit /b 1
          render -gamma 1.1 -tiff example1.tiff < example1.r3d
          if not exist example1.tiff exit /b 1
          for %%F in (example1.tiff) do if %%~zF EQU 0 exit /b 1
    files:
      source:
        - examples/
        - materials/

about:
  homepage: "http://www.bmsc.washington.edu/raster3d"
  summary: "A set of tools for generating high-quality raster images of proteins and molecules"
  description: |
    Raster3D is a set of tools for generating high quality raster images of proteins or other molecules.
    The core program renders spheres, triangles, cylinders, and quadric surfaces with specular highlighting, Phong shading, and shadowing.
    It uses an efficient software Z-buffer algorithm which is independent of any graphics hardware.
    Ancillary programs process atomic coordinates from PDB files into rendering descriptions for pictures composed of ribbons, space-filling atoms, bonds, ball+stick, etc.
    Raster3D can also be used to render pictures composed in other programs such as [Molscript](http://www.bmsc.washington.edu/raster3d/#pointers) in glorious 3D with highlights, shadowing, etc.
    Output is to pixel image files with 24 bits of color information per pixel.
  license: Artistic-2.0
  license_file: Artistic_License_V2
  documentation: http://www.bmsc.washington.edu/raster3d/html/raster3d.html

extra:
  recipe-maintainers:
    - eunos-1128
